# Generated by Django 4.0.1 on 2022-01-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exjawcc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='slug',
            field=models.SlugField(blank=True, max_length=32, unique=True),
        ),
    ]
